program: src/models/train_model.py
method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    values: [1, 3, 5]
  batch_size: 
    values: [20, 50, 500]
  learning_rate:
    min: 0.0001
    max: 0.1

early_terminate:
  type: hyperband
  max_iter: 27
  s: 2

command:
  - python
  - ${program}