name: "Run flake8"

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .