name: "Run isort"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install isort
        run: pip install isort

      - name: Run isort
        run: isort -rc .