name: "Run tests"

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
      - name: Install pytest
        run: pip install pytest

      - name: Test with pytest
        run: pytest -v